apiVersion: v1
data:
  chirpstack-application-server.toml: |
    # See https://www.chirpstack.io/application-server/install/config/ for a full
    # configuration example and documentation.

    [postgresql]
    dsn="postgres://chirpstack_as:chirpstack_as@chirpstack-postgresql/chirpstack_as?sslmode=disable"

    [redis]
    url="redis://chirpstack-redis:6379"

    [application_server.integration.mqtt]
    server="tcp://mosquitto-internal:1882"
    #username=""
    #password=""

    [application_server.api]
    public_host="chirpstack-application-server:8001"

    [application_server.external_api]
    bind="0.0.0.0:8080"
    jwt_secret="AHAHAHYOUDIDNTSAYTHEMAGICWORD"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: chirpstack-application-server-config
